name: weather_final_proj
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  fl_chart: ^0.66.2
  flutter:
    sdk: flutter
  geolocator: ^11.0.0
  http: ^1.2.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - image/background1.png
    - image/background3.png
    - image/background5.png
